# Generated by Django 5.0 on 2025-12-09 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('restricted_dept', models.CharField(blank=True, max_length=50, null=True)),
                ('offering_dept', models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering')], help_text='Department that owns/offers this minor branch.', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('offering_dept', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering')], help_text='Department that offers this Open Elective.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Preference Window', max_length=100)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MIN_PERCENTAGE', 'Minimum Percentage Required'), ('DEPARTMENT_BLOCK', 'Blocked Departments')], max_length=20)),
                ('value', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='allotment.minorbranch')),
            ],
            options={
                'ordering': ['-is_active', 'rule_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OEEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MIN_PERCENTAGE', 'Minimum Percentage Required'), ('DEPARTMENT_BLOCK', 'Blocked Departments')], max_length=20)),
                ('value', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oe_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='allotment.openelective')),
            ],
            options={
                'ordering': ['-is_active', 'rule_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering')], max_length=50)),
                ('percentage', models.FloatField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OEPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('oe_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.openelective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oe_preferences', to='allotment.student')),
            ],
        ),
        migrations.CreateModel(
            name='OEAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oe_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.openelective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.student')),
            ],
        ),
        migrations.CreateModel(
            name='MinorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('minor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.minorbranch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_preferences', to='allotment.student')),
            ],
        ),
        migrations.CreateModel(
            name='MinorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.minorbranch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.student')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleMinorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('minor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.minorbranch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_minor_preferences', to='allotment.student')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleMinorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.minorbranch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.student')),
            ],
        ),
    ]
