# Generated by Django 5.0 on 2025-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorpreference',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
