# Generated by Django 5.0 on 2025-12-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_minorpreference_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minorpreference',
            name='explanation',
        ),
        migrations.AddField(
            model_name='minorallocation',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
