# Generated by Django 5.0 on 2026-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_remove_minorpreference_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('CLEAR', 'No Backlog'), ('REASSESSMENT_PENDING', 'Reassessment Pending'), ('CLEARED_AFTER_REASSESSMENT', 'Cleared After Reassessment'), ('FAILED_REASSESSMENT', 'Failed Reassessment')], default='CLEAR', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='backlog_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='has_backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reassessment_applied',
            field=models.BooleanField(default=False),
        ),
    ]
