# Generated by Django 5.0 on 2026-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0005_allocationstatistics_allocationappeal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('preference_created', 'Preference Created'), ('preference_updated', 'Preference Updated'), ('preference_deleted', 'Preference Deleted'), ('allocation_created', 'Allocation Created'), ('allocation_updated', 'Allocation Updated'), ('login', 'Login'), ('logout', 'Logout'), ('export_data', 'Data Exported')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AllocationAppeal',
        ),
    ]
