# Generated by Django 5.0 on 2026-01-18 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0006_alter_auditlog_action_delete_allocationappeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('preference_created', 'Preference Created'), ('preference_updated', 'Preference Updated'), ('preference_deleted', 'Preference Deleted'), ('allocation_created', 'Allocation Created'), ('allocation_updated', 'Allocation Updated'), ('allocation_run', 'Allocation Run'), ('allocation_cleared', 'Allocation Cleared'), ('student_created', 'Student Created'), ('student_updated', 'Student Updated'), ('login', 'Login'), ('logout', 'Logout'), ('export_data', 'Data Exported'), ('bulk_import', 'Bulk Import')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='doubleminorallocation',
            unique_together={('student', 'minor_branch')},
        ),
        migrations.AlterUniqueTogether(
            name='minorallocation',
            unique_together={('student', 'minor_branch')},
        ),
        migrations.AlterUniqueTogether(
            name='oeallocation',
            unique_together={('student', 'oe_subject')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='allotment_a_timesta_7c65f2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='allotment_a_user_id_37f641_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='allotment_a_action_ba825a_idx'),
        ),
        migrations.AddIndex(
            model_name='doubleminorallocation',
            index=models.Index(fields=['student'], name='allotment_d_student_9a2832_idx'),
        ),
        migrations.AddIndex(
            model_name='doubleminorallocation',
            index=models.Index(fields=['minor_branch'], name='allotment_d_minor_b_54a13e_idx'),
        ),
        migrations.AddIndex(
            model_name='minorallocation',
            index=models.Index(fields=['student'], name='allotment_m_student_f19e48_idx'),
        ),
        migrations.AddIndex(
            model_name='minorallocation',
            index=models.Index(fields=['minor_branch'], name='allotment_m_minor_b_300cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='oeallocation',
            index=models.Index(fields=['student'], name='allotment_o_student_d3a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='oeallocation',
            index=models.Index(fields=['oe_subject'], name='allotment_o_oe_subj_89a71b_idx'),
        ),
    ]
