# Generated by Django 5.0 on 2026-01-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0007_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubleminorpreference',
            options={'ordering': ['student', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='minorpreference',
            options={'ordering': ['student', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='oepreference',
            options={'ordering': ['student', 'priority']},
        ),
        migrations.AlterUniqueTogether(
            name='doubleminorpreference',
            unique_together={('student', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='minorpreference',
            unique_together={('student', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='oepreference',
            unique_together={('student', 'priority')},
        ),
    ]
