# Generated by Django 5.0 on 2026-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0009_reassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('preference_created', 'Preference Created'), ('preference_updated', 'Preference Updated'), ('preference_deleted', 'Preference Deleted'), ('allocation_created', 'Allocation Created'), ('allocation_updated', 'Allocation Updated'), ('allocation_run', 'Allocation Run'), ('allocation_cleared', 'Allocation Cleared'), ('student_created', 'Student Created'), ('student_updated', 'Student Updated'), ('login', 'Login'), ('logout', 'Logout'), ('export_data', 'Data Exported'), ('bulk_import', 'Bulk Import'), ('reassessment_approved', 'Reassessment Approved'), ('reassessment_rejected', 'Reassessment Rejected')], max_length=50),
        ),
    ]
