# Generated by Django 5.0 on 2026-01-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0011_reassessment_document_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassessmentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('PHASE_1', 'Phase 1: Backlog Declaration'), ('PHASE_2', 'Phase 2: Results Update'), ('CLOSED', 'Closed')], default='CLOSED', max_length=20)),
                ('is_open', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reassessment',
            options={'ordering': ['-declared_at'], 'verbose_name_plural': 'Reassessments'},
        ),
        migrations.RenameField(
            model_name='reassessment',
            old_name='remarks',
            new_name='admin_remarks',
        ),
        migrations.RenameField(
            model_name='reassessment',
            old_name='reviewed_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='reassessment',
            old_name='submitted_at',
            new_name='declared_at',
        ),
        migrations.AlterUniqueTogether(
            name='reassessment',
            unique_together={('student', 'declared_at')},
        ),
        migrations.AddField(
            model_name='reassessment',
            name='backlog_details',
            field=models.TextField(default=0, help_text='Detailed information about backlogs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reassessment',
            name='backlog_subjects',
            field=models.TextField(default=1, help_text='Comma-separated subject codes/names with backlogs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reassessment',
            name='has_backlog',
            field=models.BooleanField(default=False, help_text='Student confirms having backlog'),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='results_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='update_details',
            field=models.TextField(blank=True, help_text='Additional details about clearing', null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reassessment',
            name='fail_marksheet',
            field=models.FileField(help_text='Upload fail marksheet as proof', upload_to='reassessment/fail_marksheets/'),
        ),
        migrations.AlterField(
            model_name='reassessment',
            name='passing_marksheet',
            field=models.FileField(blank=True, help_text='Upload passing marksheet after clearing', null=True, upload_to='reassessment/passing_marksheets/'),
        ),
        migrations.AlterField(
            model_name='reassessment',
            name='status',
            field=models.CharField(choices=[('DECLARED', 'Backlog Declared (Awaiting Results)'), ('UNDER_REVIEW', 'Under Review'), ('UPDATE_SUBMITTED', 'Update Submitted (Awaiting Approval)'), ('APPROVED', 'Approved - Eligible for Allocation'), ('REJECTED', 'Rejected - Ineligible')], default='DECLARED', max_length=30),
        ),
        migrations.RemoveField(
            model_name='reassessment',
            name='backlog_count',
        ),
        migrations.RemoveField(
            model_name='reassessment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='reassessment',
            name='subjects',
        ),
    ]
