# Generated by Django 5.0 on 2026-01-21 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0012_reassessmentwindow_alter_reassessment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('major_branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering')], max_length=50)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='AbscondingStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('auto_allocated', models.BooleanField(default=False)),
                ('imported_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absconding_record', to='allotment.importedstudent')),
            ],
            options={
                'ordering': ['-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_submission', to='allotment.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
                ('successful_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='importedstudent',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='allotment.studentimport'),
        ),
        migrations.AlterUniqueTogether(
            name='importedstudent',
            unique_together={('import_batch', 'roll_no')},
        ),
    ]
