# Generated by Django 5.0 on 2026-01-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0013_importedstudent_student_is_validated_student_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleminorallocation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allotment.student'),
        ),
        migrations.AlterField(
            model_name='minorallocation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allotment.student'),
        ),
        migrations.AlterField(
            model_name='oeallocation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allotment.student'),
        ),
    ]
