# Generated by Django 5.0 on 2026-01-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0014_alter_doubleminorallocation_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('roll_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('dbms_th', models.IntegerField(blank=True, null=True)),
                ('dbms_int', models.IntegerField(blank=True, null=True)),
                ('dbms_total', models.IntegerField(blank=True, null=True)),
                ('toc_th', models.IntegerField(blank=True, null=True)),
                ('toc_int', models.IntegerField(blank=True, null=True)),
                ('toc_total', models.IntegerField(blank=True, null=True)),
                ('se_th', models.IntegerField(blank=True, null=True)),
                ('se_int', models.IntegerField(blank=True, null=True)),
                ('se_total', models.IntegerField(blank=True, null=True)),
                ('dm_th', models.IntegerField(blank=True, null=True)),
                ('dm_int', models.IntegerField(blank=True, null=True)),
                ('dm_total', models.IntegerField(blank=True, null=True)),
                ('dss_th', models.IntegerField(blank=True, null=True)),
                ('dss_int', models.IntegerField(blank=True, null=True)),
                ('dss_total', models.IntegerField(blank=True, null=True)),
                ('st_th', models.IntegerField(blank=True, null=True)),
                ('st_int', models.IntegerField(blank=True, null=True)),
                ('st_total', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Results',
                'ordering': ['roll_no'],
            },
        ),
    ]
