# Generated by Django 5.0 on 2026-02-01 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0015_studentresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='allotment.student')),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['student', '-attempted_at'], name='allotment_s_student_45f8b8_idx')],
            },
        ),
    ]
