# Generated by Django 5.0 on 2026-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0017_add_offering_dept_to_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openelective',
            name='offering_dept',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering')], help_text='Department that offers this Open Elective.', max_length=50),
        ),
    ]
