# Generated by Django 5.0 on 2026-02-16 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0018_alter_openelective_offering_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='abscondingstudent',
            name='allocated_minor',
            field=models.ForeignKey(blank=True, help_text='Minor branch assigned during auto-allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absconding_allocations', to='allotment.minorbranch'),
        ),
        migrations.AddField(
            model_name='abscondingstudent',
            name='allocated_oe',
            field=models.ForeignKey(blank=True, help_text='Open elective assigned during auto-allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absconding_allocations', to='allotment.openelective'),
        ),
    ]
