# Generated by Django 5.0 on 2026-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0019_abscondingstudent_allocated_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorpreference',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True if this preference was auto-generated for an absconding student'),
        ),
        migrations.AddField(
            model_name='oepreference',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True if this preference was auto-generated for an absconding student'),
        ),
    ]
