# Generated by Django 5.0 on 2026-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0020_minorpreference_auto_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedstudent',
            name='major_branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ENTC', 'Electronics & Telecomm. Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='minorbranch',
            name='offering_dept',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ENTC', 'Electronics & Telecomm. Engineering')], help_text='Department that owns/offers this minor branch.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='openelective',
            name='offering_dept',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ENTC', 'Electronics & Telecomm. Engineering')], help_text='Department that offers this Open Elective.', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ENTC', 'Electronics & Telecomm. Engineering')], max_length=50),
        ),
    ]
