# Generated by Django 5.0 on 2026-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0021_alter_importedstudent_major_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedstudent',
            name='major_branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm. Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ENTC', 'Electronics & Telecomm. Engineering'), ('GENERAL', 'General / Not Specified')], default='GENERAL', max_length=50),
        ),
    ]
