# Generated by Django 5.0 on 2026-03-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0023_separate_preference_windows'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='preferencewindow',
            new_name='allotment_p_prefere_f24761_idx',
            old_name='allotment_p_prefere_43e357_idx',
        ),
        migrations.RenameIndex(
            model_name='preferencewindow',
            new_name='allotment_p_prefere_606566_idx',
            old_name='allotment_p_prefere_764d3c_idx',
        ),
    ]
